name: Custom_cerbero_Run_Action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Gstreamer dependencies
      run: |
          sudo apt-get -y update && sudo apt-get -y upgrade
          sudo apt-get install -y \
          python3-dev python3-distro python3-setuptools python3-pip \
          autotools-dev automake autoconf autopoint \
          libtool \
          g++ \
          make cmake pkg-config \
          bison \
          flex \
          nasm \
          libxv-dev \
          libx11-dev \
          libx11-xcb-dev \
          libpulse-dev \
          gettext \
          libxext-dev \
          libxi-dev \
          x11proto-record-dev \
          libxrender-dev \
          libgl1-mesa-dev \
          libxfixes-dev \
          libxdamage-dev \
          libxcomposite-dev \
          libasound2-dev \
          build-essential \
          gperf \
          wget \
          libxtst-dev \
          libxrandr-dev \
          libglu1-mesa-dev \
          libegl1-mesa-dev \
          git \
          xutils-dev \
          intltool \
          ccache \
          libssl-dev \
          libjson-glib-1.0-0 \
          libjson-glib-dev

    - name: git clone cerbero
      run: |
        git clone https://gitlab.freedesktop.org/gstreamer/cerbero.git /vendor/cerbero && \
        cd /vendor/cerbero && git checkout 1.22.5 && \
        ./cerbero-uninstalled -c config/cross-android-universal.cbc fetch-bootstrap && \
        ./cerbero-uninstalled -c config/cross-android-universal.cbc fetch-package gstreamer-1.0
      working-directory: ${{ github.workspace }}

    - name: package gstreamer-1.0
      run: |
        ./cerbero-uninstalled -c config/cross-android-universal.cbc bootstrap --offline && \
        ./cerbero-uninstalled -c config/cross-android-universal.cbc package gstreamer-1.0
      working-directory: vendor/cerbero

    - name: Display vendor/cerbero structure of downloaded files
      run: ls -R
      working-directory: vendor/cerbero       
