name: Custom_Docker_Run_Action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nekmo/telegram-upload:master
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - /media/data/:/docker/files/
      options: --cpus 1
    steps:
    - name: run docker
      run: |
        ls -R /app
        /usr/local/bin/python /app/telegram_upload/management.py --interactive
        ls
