name: Custom_Docker_Run_Action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nekmo/telegram-upload:master
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - /docker/files:/files
      options: --cpus 1
    steps:
    - name: Write session to file
      env:
        TLG_SESSION: ${{ secrets.TLG_SESSION }}
        APP_SESSION: ${{ secrets.APP_SESSION }}
        TELEGRAM_UPLOAD_CONFIG_DIRECTORY: ~/.config
      run: |
        mkdir -p ~/.config/
        echo "$TLG_SESSION" | base64 --decode > ~/.config/telegram-upload.session
        echo "$APP_SESSION" > ~/.config/telegram-upload.json
        cat ~/.config/telegram-upload.json
        ls -R /files
    - name: run docker
      run: |
        /usr/local/bin/python /app/telegram_upload/management.py --config=~/.config/telegram-upload.json upload text.txt
    # /app:
    # telegram_upload
    
    # /app/telegram_upload:
    # __init__.py
    # _compat.py
    # client.py
    # config.py
    # exceptions.py
    # files.py
    # management.py
    # utils.py
    # video.py        
