# The 32 and 64 bit version of these actions should be kept in sync
name: GST Android 64-bit Release

on:
  push:
  pull_request:

env:
  GStreamerVersion: 1.22.5

jobs:
  Android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: [arm64-v8a]


    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
  
      - name: Setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e
          local-cache: true          

      - name: Download GStreamer
        run: |
          wget https://gstreamer.freedesktop.org/data/pkg/android/${{ env.GStreamerVersion }}/gstreamer-1.0-android-universal-${{ env.GStreamerVersion }}.tar.xz

      - name: Build
        run: |
          echo "NDK_PROJECT_PATH=${{ steps.setup-ndk.outputs.ndk-path }}"
          export NDK_PROJECT_PATH=${{ steps.setup-ndk.outputs.ndk-path }}
          export TARGET_ARCH_ABI=${{ matrix.abi }}
          mkdir gstreamer_android
          tar -xf gstreamer-1.0-android-universal-${{ env.GStreamerVersion }}.tar.xz -C $(pwd)/gstreamer_android/
          export GSTREAMER_ROOT_ANDROID=$(pwd)/gstreamer_android
          mkdir gstreamer
          # cp gstreamer-android/* gstreamer/jni
          echo "\n\n=== Building GStreamer ${{ env.GStreamerVersion }} for target ${{ matrix.abi }} with ${NDK_APPLICATION_MK} ==="
          export NDK_PROJECT_PATH=$(pwd)/gstreamer-android
          ndk-build "NDK_APPLICATION_MK=Android.mk" APP_ABI=${{ matrix.abi }} APP_PLATFORM=android-21 NDK_LIBS_OUT=$(pwd)  
          
      - name: Copy libc++_shared.so
        run: |
           cp ${{ steps.setup-ndk.outputs.ndk-path }}/sources/cxx-stl/llvm-libc++/libs/${{ matrix.abi }}/libc++_shared.so ${{ matrix.abi }}/

      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          name: AndroidGStreamer
          path: |
            */libgstreamer_android.so
            */libc++_shared.so
